### ISSUE TITLE
Support for DotNet Core

### ISSUE THREAD

**Issue by Brumawen** [samuelneff/MimeTypeMap#53]
Hello, Is there a roadmap for providing support for DotNet Core?

**Comment by 0xdeafcafe** [comment]
I made a fork that supports .NET Standard as we needed to use it - https://github.com/HelmGlobal/MimeTypeMap

**Comment by samuelneff** [comment]
Thanks for the link.

If you want to submit your updates as a pull request with a differently named solution and project file (so that both the old and new ones can live side-by-side) I'll be happy to merge them. Other people have asked about it too and unfortunately I don't do any .NET work anymore myself so haven't had the incentive (or already installed tooling) to update it myself.

Sam

**Comment by markusschaber** [comment]
I guess there won't be any NuGet package for the new .NET Core enabled version?

Is anyone willing to "adopt" this package?

**Comment by FuchsiaSoft** [comment]
I use this a fair bit actually so if no one else is forthcoming I can look at sorting out a nuget for it.

Not my repo though so would have to be from a fork.

**Comment by rmja** [comment]
@william-gross could you update the nuget package to the new version?

**Comment by ryanbuening** [comment]
https://www.nuget.org/packages/MediaTypeMap.Core
