### ISSUE TITLE
Strong naming and signing missing

### ISSUE THREAD

**Issue by intval** [samuelneff/MimeTypeMap#63]
Unusable together with signed assemblies, resulting in
```
Could not load file or assembly 'MimeTypeMap, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

**Comment by kmccmk9** [comment]
Same result here. This is pretty critical for our project.

**Comment by kmccmk9** [comment]
I have successfully signed this using a test certificate. If someone could guide me through the nuget deploy process, I'd be happy to work getting it up there for others to use.

**Comment by zbarrier** [comment]
Having same problem with version 2.3.3.  It actually says it can't load Version 2.3.2 even though the installed version is 2.3.3.  Is this going to be a problem with each version?  This is critical to a project.

**Comment by ImrePyhvel** [comment]
Same here. cannot be used in strongly named projects.

Why is this issue closed without a resolution? This is misleading.

**Comment by samuelneff** [comment]
This is closed because at the time I didn't manage any NuGet package so it was an issue to be dealt with by the NuGet package maintainers.

I have since started publishing an official NuGet package. If that ones still has a problem, please let me know by opening a new issue.

The current official version is 1.0.11.

https://www.nuget.org/packages/MimeTypeMapOfficial
