### ISSUE TITLE
New mime types

### ISSUE THREAD

**Issue by BoantaIonut** [samuelneff/MimeTypeMap#85]
Hello.
Can you please add [F4V](https://www.filedesc.com/en/file/f4v), [GXF](https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x/conf/mime.types), [MXF](https://www.filedesc.com/en/file/mxf), [ISMA](https://www.filedesc.com/en/file/isma) and [ISMV](https://www.filedesc.com/en/file/ismv) to the mime type list?
I know that the last two have the default mime type that is returned if the extension is not found in the map, but it is nice to have them there for completion purposes.
Thank you.

**Comment by samuelneff** [comment]
Added. Thanks.

**Comment by PierceLBrooks** [comment]
`.isma` & `.ismv` are vended from `.ism` manifests which can have the "`application/vnd.ms-sstr+xml`" mime type according to my research. I have been recording my findings informally at https://gist.github.com/PierceLBrooks/b3389a2ca790b05ced89f2e4d5940680

**Comment by samuelneff** [comment]
I can't find any authoritative source associating `application/vnd.ms-sstr+xml` with a file extension. I found an article linking a URL inside a `.ism` file to this but it appears it the `.ism` file itself is a type of archive and `application/vnd.ms-sstr+xml` refers to the manifest inside the file.

https://learn.microsoft.com/en-us/azure/media-services/azure-media-player/azure-media-player-url-rewriter

If you have an authoritative please open a new issue (this issue was closed as resolved) with a link.

Thanks for the information though. I enjoyed researching it.
