### ISSUE TITLE
Requested mime type is not registered: application/zip    at MimeTypes.MimeTypeMap.GetExtension(String mimeType)

### ISSUE THREAD

**Issue by HadiNass** [samuelneff/MimeTypeMap#87]
I tried to upload a zip file using my .net webapi but failed due to this. I made a util method to help me uploading files:

        private string GetExtensionFromFileHeader(HttpContent file)
        {
            return MimeTypeMap.GetExtension(file.Headers.ContentType.ToString());
        }

But it's crashing when I upload zip files (works fine with everything else I tried so far from images to pdfs and words)

Am I missing something?

**Comment by samuelneff** [comment]
"Crashing"? What exactly is it doing? Do you get an exception? What is the exact message? What is the full stack trace?

What is the actual value of `file.Headers.ContentType.ToString()` ?

The content-type sent from the client is specified from the client. You can't guarantee that it will be the correct content type or one that is mapped.

**Comment by Abdulhameed-A** [comment]
This due to `application/zip` is not registered in the mapping dictionary, the one that is mapped to `.zip` is `application/x-zip-compressed`, to solve this issue you need to add `application/zip` as another mapping value for `.zip`.

I have used your lovely file [MimeTypeMap.cs](https://github.com/samuelneff/MimeTypeMap/blob/master/src/MimeTypes/MimeTypeMap.cs) in my [FileBarrier.Core Library](https://github.com/Abdulhameed-A/FileBarrier.Core) and done some modifications to it, so feel free to check it out.

**Comment by dnmh-psc** [comment]
@samuelneff Why is this closed? - it is still an issue.

**Comment by samuelneff** [comment]
@dnmh-psc I'm sorry you're running into similar issues. Hopefully this can help.

This specific issue was closed because the OP never answered the follow-up questions required to fully understand the original report. The information that was provided also indicated he was using a modified version of the library and the mapping he referenced did not match the mapping in the official version. 

Several people have posted modified versions to NuGet, which they were allowed to do. However, those versions have some differences in the mappings. Sometimes reports come in here from people that are not using the official library, usually without realizing it. I've written to the other publishers to ask them to remove their versions to alleviate confusion but as far as I know none have done so. To be clear they are fully within their rights, the code is open-source, but publishing modified versions without clearly differentiated names has created a lot of confusion.

If you are having issues make sure you are using the official version and post a new issue here with the version number and details of what you're encountering.

https://www.nuget.org/packages/MimeTypeMapOfficial

Thanks,

Sam
